<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="iotlab-m3.tests_evtimer_msg" skips="0" tests="1" time="8.914"><properties><property name="RIOT_VERSION" value="2019.07-devel-249-g5bb49-HEAD"/></properties><testcase classname="iotlab-m3.tests_evtimer_msg" file="tests/01-run.py" line="15" name="test.tests.01-run.testfunc" time="8.882941007614136"><system-out>ssh -t iotlab@saclay.iot-lab.info &apos;socat - tcp:m3-1.saclay.iot-lab.info:20000&apos;
At   3956 ms received msg 3: &quot;supposed to be 3954&quot;
�main(): This is RIOT! (Version: buildtest)
Testing generic evtimer (start time = 1 ms)
Are the reception times of all 4 msgs close to the supposed values?
If yes, the tests were successful
�main(): This is RIOT! (Version: buildtest)
Testing generic evtimer (start time = 1 ms)
Are the reception times of all 4 msgs close to the supposed values?
If yes, the tests were successful
At    661 ms received msg 0: &quot;supposed to be 659&quot;
.At   1002 ms received msg 1: &quot;supposed to be 1000&quot;
.At   1502 ms received msg 2: &quot;supposed to be 1500&quot;
.At   3956 ms received msg 3: &quot;supposed to be 3954&quot;
.
All tests successful

</system-out></testcase></testsuite>